spring:
  datasource:
    driverClassName: org.h2.Driver
    generate-unique-name: false
    name: tacocloud
    url: jdbc:h2:mem:tacocloud
    username: rafic
    password: password
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/oauth2/jwks

server:
  port: 8081